### ISSUE TITLE
Usernames on marzneshin

### ISSUE THREAD

**Issue by Ilaprgg2** [erfjab/migration#5]
سلام 
ممنون از اسکریپت کاربردیتون
وقتی کاربرها به مرزنشین انتقال پیدا میکنند یه عدد هم در کنار اسمشون قرار میگیره. چطور میشه از اسکریپت حذفش کرد؟

**Comment by erfjab** [comment]
درود و وقت بخیر
این مشکل نیست، روشی برای جلوگیری از مشکل مربوط به مرزبان هست. 
با آپدیت بعدی حل خواهد شد.
